### PR TITLE
Add basic countdown functionality

### PR DESCRIPTION
**Pull request by HeyChobe**
- Add countdown from 20 to 0 seconds
- Add countdown.js with this functionality
- Add format for background.html

### CODE REVIEW

**Review by chinmaychahar — COMMENTED** [review]
Countdown doesn't make any changes to "20 seconds". Did you try running the changes locally?

**Comment by HeyChobe** [comment]
Yes, I ran the changes locally before committing, I have no idea why you can't see the changes, I send a gif at x2 speed showing the expected behavior

countdown

I had to update the extension in the extension manager each time to see the current changes, did you try it?

**Review by chinmaychahar — COMMENTED** [review]
Works as expected

**Review by chinmaychahar — CHANGES_REQUESTED** [review]
One last thing, can the timer be set to 40 initially? The instruction guide includes 10 secs after and before as well so total adds up to 40

**Comment by HeyChobe** [comment]
> One last thing, can the timer be set to 40 initially? The instruction guide includes 10 secs after and before as well so total adds up to 40

Sure

**Comment by HeyChobe** [comment]
The index.js file has a comments of the previous interval, would I clean those lines?

**Comment by chinmaychahar** [comment]
> The index.js file has a comments of the previous interval, would I clean those lines?

Yes

**Review by chinmaychahar — APPROVED** [review]
Great, thanks for the contribution!

**Comment by chinmaychahar** [comment]
Hey @HeyChobe could you please share your email id?

**Pull request merged**
